### ISSUE TITLE
CRUX Port

### ISSUE THREAD

**Issue by prologic** [damicon/zfswatcher#10]
Hi Just wnated to share a CRUX port I've put together for ``zfswatcher:

```#!bash
# Description:  ZFS pool monitoring and notification daemon
# URL:          http://zfswatcher.damicon.fi/
# Maintainer:   ames Mills, prologic at shortcircuit dot net dot au
#
# Depends on:   go

name=zfswatcher
version=0.03
release=1
source=(http://shortcircuit.net.au/~prologic/distfiles/$name-$version.tar.gz)

build() {
    cd $name-$version

    # Fix go path
    sed -i -e 's|/usr/local/go/bin/go|/usr/bin/env go|g' Makefile

    make

    make DESTDIR=$PKG install

    # Fix man paths
    mv $PKG/usr/share/man $PKG/usr
}
```

Note the ``sed`` and ``mv`` hacks I had to do? Perhaps these could be configurable if not already?

**Comment by snabb** [comment]
I do not see why you do not just set the `GO` and `mandir` Makefile variables on the `make` command line. It is much simpler that way. Any variables specified on the `make` command line override the defaults set in the Makefile. You are already doing this with the `DESTDIR` variable.

**Comment by prologic** [comment]
Yeah no worries I guess I can :)
