### ISSUE TITLE
Request for help with Apache2 VirtualHost config

### ISSUE THREAD

**Issue by 3ceepio** [damicon/zfswatcher#14]
Thanks for this great utility, I've been using it with the built-in web server on an alternate port but now trying to move it to a named virtual host but struggling to find the correct DocumentRoot. I'm pointing the DocumentRoot to /usr/share/zfswatcher/www but only getting the directory listing.

My config in /etc/apache2/sites-enabled/zfswatcher.conf:

<VirtualHost *>
DocumentRoot "/usr/share/zfswatcher/www"
ServerName zfswatcher
<Directory />
Options FollowSymLinks
AllowOverride None
</Directory>
<Directory "/usr/share/zfswatcher/www">
Options Indexes FollowSymLinks MultiViews
AllowOverride None
Order allow,deny
allow from all
Require all granted
</Directory>
</VirtualHost>

Where should this be pointed? Thanks.

**Comment by rouben** [comment]
You need to set up Apache to act as a reverse proxy to the built-in zfswatcher web server. So tell zfswatcher to run on localhost:8080 (or whatever port you want), then point Apache as a reverse proxy to localhost:8080.

[Tutorial link](https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension).

**Comment by 3ceepio** [comment]
Many thanks, it works great.
